### ISSUE TITLE
bulk_download_metadata.py should handle projects without any runs

### ISSUE THREAD

**Issue by willbenica** [neptune-ai/examples#291]
When backing up all projects for a team using the `bulk_download_metadata.py` script, I ran into the issue that a project without any runs or other meta information would cause the entire script to fail.

```bash
Logs available at neptune_backup_20240117150602.log
Enter the download path (will be created if it doesn't exist). Leave blank to download to current directory:
Download remotely tracked artifacts? (y|n):y
Projects found: ['team/project_1', 'team/project_2', 'team/project_3', 'team/project_4', 'team/project_5', 'team/project_no_runs']
Enter projects you want to back up (comma-separated, no space) ('all' to export all projects): team/project_no_runs
Starting backup. View logs at neptune_backup_20240117150602.log. Press Ctrl/Cmd + C to cancel at any time
Total progress:   0%|                                                                                                                                                               | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/Users/me/neptune_backups/bulk_download_metadata.py", line 130, in <module>
    runs = list(_project.fetch_runs_table(columns=[]).to_pandas()["sys/id"])
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/me/neptune_backups/.venv/lib/python3.12/site-packages/pandas/core/frame.py", line 3893, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/neptune_backups/.venv/lib/python3.12/site-packages/pandas/core/indexes/range.py", line 418, in get_loc
    raise KeyError(key)
KeyError: 'sys/id'
Total progress:   0%|                                                                                                                                                               | 0/1 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/Users/me/neptune_backups/bulk_download_metadata.py", line 130, in <module>
    runs = list(_project.fetch_runs_table(columns=[]).to_pandas()["sys/id"])
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/me/neptune_backups/.venv/lib/python3.12/site-packages/pandas/core/frame.py", line 3893, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/me/neptune_backups/.venv/lib/python3.12/site-packages/pandas/core/indexes/range.py", line 418, in get_loc
    raise KeyError(key)
KeyError: 'sys/id'
```

Locally to get the backup to run, I just wrapped the creation of the DF based on the run IDs in a `try`/`except` block. This seems to work.
Unsure of what the Error message should be:

```python
except KeyError:
  logging.error("Error creating the initial list of job runs, most likely there are 0 runs in this project.")
```

**Comment by willbenica** [comment]
@SiddhantSadangi,
This is great and resolves my issue!
Thanks
